# Generated by Django 2.2.4 on 2019-08-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'その他')])),
                ('address', models.CharField(max_length=128)),
                ('jobs', models.CharField(max_length=1024)),
                ('note', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
